//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lga
    {
        public int Id { get; set; }
        public string StateCode { get; set; }
        public string LgaName { get; set; }
        public string LgaCode { get; set; }
    }
}
