//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModulePersonLnk
    {
        public int Id { get; set; }
        public string ReporterId { get; set; }
        public int ModuleId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Module Module { get; set; }
    }
}
