//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RMAEntities : DbContext
    {
        public RMAEntities()
            : base("name=RMAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Lga> Lgas { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<ModulePersonLnk> ModulePersonLnks { get; set; }
        public virtual DbSet<Party> Parties { get; set; }
        public virtual DbSet<PartyPersonLnk> PartyPersonLnks { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<PollingUnit> PollingUnits { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Vote> Votes { get; set; }
        public virtual DbSet<Ward> Wards { get; set; }
    }
}
