//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int Id { get; set; }
        public int ResultId { get; set; }
        public int PartyId { get; set; }
        public int Vote1 { get; set; }
    
        public virtual Party Party { get; set; }
        public virtual Result Result { get; set; }
    }
}
